# Generated by Django 3.1.5 on 2021-06-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.CharField(default='patient', max_length=25, verbose_name='Category type of the user'),
        ),
    ]
