# Generated by Django 3.1.5 on 2021-07-24 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='uuid'),
        ),
    ]
